### ISSUE TITLE
I'm trying to understand how the app works internally. Could you provide documentation of these APIs?

### ISSUE THREAD

**Issue by 25077667** [ailabstw/social-distancing-android#3]
https://github.com/ailabstw/social-distancing-android/blob/aee80856ae1b19cc3f961d1f929944ff2300030e/SocialDistance/src/main/java/tw/gov/cdc/exposurenotifications/Secrets.kt#L1:L43

Could you provide documentation of these "secret" functions? Thanks.

**Comment by walkingice** [comment]
not sure what kind of documentation you are looking for. If you want to understand how it works, the implementation is supposed to be this file

https://github.com/ailabstw/social-distancing-android/blob/b3e4cc9d7cf0312a8a0cd7f2476185566afc6fa4/SocialDistance/src/main/cpp/secrets.cpp

**Comment by catcutecat** [comment]
Hi, we use [this gradle plugin](https://github.com/klaxit/hidden-secrets-gradle-plugin) to hide secrets in the project.
