### ISSUE TITLE
Please consider adding configuration option that only notifies when "necessary"

### ISSUE THREAD

**Issue by stevencch99** [ailabstw/social-distancing-android#5]
We're don't really care about _"No exposure detected"_, right?
How about only notifies users when **"Exposure detected"**, instead of pop-up _"No exposure detected"_ every day at a random time?

**Comment by catcutecat** [comment]
"No exposure detected" only pop-up during 18:00 - 22:00 at most once every day. The main purpose is to let users know that the app is continuing working. If the app stops pop-up "No exposure detected" notifications, users may try to launch the app and take necessary actions.

**Comment by PichuChen** [comment]
Maybe @stevencch99 want a SharedPreference key and user interface for turn off "No exposure detected"?

**Comment by PichuChen** [comment]
I remember that Android notifications can be setting by [`channel`](https://developer.android.com/training/notify-user/channels), Would it be helpful if setting the channel and let user set them by themselves?

Maybe we can do less UI work?

**Comment by catcutecat** [comment]
Good advice. I prefer a SharedPreference key and add a switch in the settings page because NotificationChannel is only available after Android 8.0 and not all users know how to set it. We’ll consider adding this change for both Android and iOS in the upcoming version :D
